[package]
name = "pbr"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.29.2", features = ["rand"] }
image = { version = "0.25.5", features = ["rayon"] }
num = "0.4.3"
rand = "0.8.5"
rayon = "1.10.0"
